FROM ubuntu:18.10

RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y \
    && apt-get autoremove -y && apt-get autoclean -y \
    && apt-get install -y dnsutils net-tools iputils-ping
